### ISSUE TITLE
Some information Isn't correct.

### ISSUE THREAD

**Issue by OneEyedOwlLeaderOfGbcOfficial** [JaxOffTheHook/IceStationZPlugin-Yunix#1]
Its Owl.|gbc. i really like that you show this but i never used the plugin nor downloaded it. he does not have my ip adress as i did nothing where he could have took my ip/ID from. well yeah hes using a ip grabber but he never banned me or any member of the Gbc collective exept for $4GE wich will not have a relation to the collective anymore due to the shit he've done. but thanks for this informative site.

**Comment by JaxOffTheHook** [comment]
hi, I am almost never online, but I was working on the repo and saw your issue.
the plugin seems to ban people yunix collects onto a server. we do not know yet what type, or were.
however, we do know certain people including you have been banned from using the plugin. while other people who are not as active have not.

**Comment by OneEyedOwlLeaderOfGbcOfficial** [comment]
i did notused the plugin wich is funny after all. if you got this information from yunix's server,its a lie.

i see how active you try to do something. i may got smthn what interessts you. any way of communicating?

**Comment by OneEyedOwlLeaderOfGbcOfficial** [comment]
would send you a discord invite link. (no worries will dlete the server after i got ur name if you got discord so we do not have to swap them in here)

**Comment by JaxOffTheHook** [comment]
my discord is JaxOnOff#8138
I sometimes am online

**Comment by OneEyedOwlLeaderOfGbcOfficial** [comment]
you're sure about giving out your name?

**Comment by JaxOffTheHook** [comment]
what name?

**Comment by OneEyedOwlLeaderOfGbcOfficial** [comment]
nvm
added you

**Comment by OneEyedOwlLeaderOfGbcOfficial** [comment]
we gotta talk a bit

**Comment by OneEyedOwlLeaderOfGbcOfficial** [comment]
or msg
